<?php
// Here you can initialize variables that will be available to your tests

define('ADMIN_TOKEN', 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoicGllcnJlIiwiaWQiOiIxIiwicGVybWlzc2lvbnMiOlsiZW50cmllcy5jcmVhdGUiLCJlbnRyaWVzLnJlYWQiLCJlbnRyaWVzLnVwZGF0ZSIsImVudHJpZXMuZGVsZXRlIiwicm9sZXMuY3JlYXRlIiwicm9sZXMucmVhZCIsInJvbGVzLnVwZGF0ZSIsInJvbGVzLmRlbGV0ZSIsInVzZXJzLmNyZWF0ZSIsInVzZXJzLnJlYWQiLCJ1c2Vycy51cGRhdGUiLCJ1c2Vycy5kZWxldGUiXSwicm9sZSI6IkFkbWluIn19.ipZsmPbB1HVmo8umX-hS5o3kXf9Y2XLKhDaWdrethkM');
define('MEMBER_TOKEN', 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoicGV0ZXJjaGVuIiwiaWQiOiIyIiwicGVybWlzc2lvbnMiOlsiZW50cmllcy5jcmVhdGUiLCJlbnRyaWVzLnJlYWQiLCJlbnRyaWVzLnVwZGF0ZSIsImVudHJpZXMuZGVsZXRlIl0sInJvbGUiOiJNZW1iZXIifX0.c4zh5bl0SEUb2iVDXJEGmQb7-zB0jq1bVvNPS5CHOw0');
